# Basic setting
c_val: 0.75
# threshold_type: [time, generation_num]
threshold_type: generation_num
hours: 0.5
generation_num: 1000
output_dir: result/testing
model_setting:
  model_json: model/8992HCs/model.tf25.json
  model_weight: model/8992HCs/model.tf25.best.ckpt.h5
token: model/8992HCs/tokens.pkl
reward_setting:
  reward_module: reward.chem_sim_reward
  reward_class: CBDock_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: True
checkpoint_load: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 4
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

# User setting
host_pdbqt: reward/data/host_aligned.pdbqt
host_sdf: reward/data/host_aligned.sdf
host_en: -157089.5126460131
molgen_n_confs: 6
molgen_rmsd_threshold: 0.35
vina_num_rotations: 5
vina_num_translations: 5
centroid_diff_threshold: 4
cavity_atoms_threshold: 6

# Parrallelisation strategy
leaf_parallel: True
# Number of leaves simultaneously
leaf_parallel_num: 4
