dataset: ./16k_zinc_small.smi
output_model_dir: ./model
output_token: ./model/tokens.pkl
use_selfies: False

dropout_rate: 0.3
rec_dropout_rate: 0
learning_rate: 0.001
epoch: 100
batch_size: 512
validation_split: 0.1
units: 256
maxlen: 82
