# Basic setting
c_val: 0.5
# threshold_type: [time, generation_num]
threshold_type: generation_num
hours: 1
generation_num: 25000
output_dir: result/uniqueness_tests/atom_pair_PCA_kde
model_setting:
  model_json: model/HCs/model.tf25.json
  model_weight: model/HCs/model.tf25.best.ckpt.h5
token: model/HCs/tokens.pkl
reward_setting:
  reward_module: reward.uniqueness_score_reward
  reward_class: uniqueness_score_atom_pair_kde

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: False
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

# User setting
mol_embed_pipeline: /home/andyt/DProjects/DMCTS/VINA_ChemTSv2/reward/mol_embedding_pipelines/atom_pair_PCA_pipe.pkl
kde: /home/andyt/DProjects/DMCTS/VINA_ChemTSv2/reward/mol_embedding_pipelines/atom_pair_PCA_kde.pkl
# For uniqueness, either max_density_point (distance from), or kde (minimise kernel density estimate)
max_density_point: [0.1246, 0.2772]
max_density: 0.2862